In [3]:
import pymorphy2
morph = pymorphy2.MorphAnalyzer()

In [2]:
pip install pymorphy2

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 55 kB 2.0 MB/s 
     |████████████████████████████████| 8.2 MB 8.2 MB/s 


In [4]:
import re

In [5]:
import numpy as np

In [6]:
import pandas as pd   #  pip install pandas

In [7]:
import string
print(string.punctuation)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


# Начинаем работать с файлом

In [245]:
f = open('1994.txt', "r")
text = f.read()

In [299]:
#text = text.lower()

In [246]:
spec_chars = string.punctuation + '\n\xa0«»\t—…' 

In [247]:
def remove_chars_from_text(text, chars):
    return "".join([ch for ch in text if ch not in chars])

In [248]:
text[:100]

'11 января 1994\n\n\nЗАСЕДАНИЕ ПЕРВОЕ\nЗдание Государственной Думы. Зал заседаний. 11 января 1994 года. 1'

In [249]:
text_split = re.split("((\w+ [А-Я|A-Z].[А-Я|A-Z].,)|(Председательствующий.))", text)
text_split[:10]

['11 января 1994\n\n\nЗАСЕДАНИЕ ПЕРВОЕ\nЗдание Государственной Думы. Зал заседаний. 11 января 1994 года. 10 часов. Заседание открывает старейший по возрасту депутат Государственной Думы Г.Г.Лукава.\n',
 'Председательствующий.',
 None,
 'Председательствующий.',
 ' Дорогие депутаты Государственной Думы! Прошу в течение примерно двух минут занять места. И второе. В вашем распоряжении аппарат, в том числе технический, для решения всех вопросов. Я прошу занять места. Приступим к работе. Граждане великой России! Россияне! Уважаемые депутаты Государственной Думы, уважаемые гости! В это мгновение взоры России, да и всего мира, обращены к Москве, к этому залу, где начинает работу Государственная Дума. По поручению старейшин Государственной Думы горячо и сердечно поздравляю с избранием вас в Государственную Думу и с началом работы - этим очень важным и знаменательным событием для России. (Аплодисменты.) Начало нашей работы совпадает с очень сложными процессами, которые происходят в нашей стране.

In [250]:
c = []
texts = text_split
strokaAll = ''
strokaWith = ''
strokaWithout = ''
for txt in texts:
    if re.match(r'((\w+ [А-Я|A-Z].[А-Я|A-Z].,)|(Председательствующий.))', str(txt)):
        strokaAll = strokaWith + strokaWithout
        c.append(strokaAll)
        strokaAll = ''
        strokaWith = ''
        strokaWithout = ''
        strokaWith += txt
    else:
        if txt is not None:
            strokaWithout += txt
    

In [251]:
df = pd.DataFrame(c)
print(df)

                                                       0
0      11 января 1994\n\n\nЗАСЕДАНИЕ ПЕРВОЕ\nЗдание Г...
1                                  Председательствующий.
2      Председательствующий. Дорогие депутаты Государ...
3                                          Апарина А.В.,
4      Апарина А.В., избирательное объединение "Комму...
...                                                  ...
34863                              Председательствующий.
34864  Председательствующий. Нет, Владимир Борисович,...
34865                              Председательствующий.
34866  Председательствующий. Снимаете? Снял. Хорошо. ...
34867                              Председательствующий.

[34868 rows x 1 columns]


In [252]:
cols = df.columns

for column in cols: 
  print(column)

0


In [253]:
# Переименнуем название колонок
df.rename(columns={0: 'text'}, inplace=True)

In [254]:
df

text
0      11 января 1994\n\n\nЗАСЕДАНИЕ ПЕРВОЕ\nЗдание Г...
1                                  Председательствующий.
2      Председательствующий. Дорогие депутаты Государ...
3                                          Апарина А.В.,
4      Апарина А.В., избирательное объединение "Комму...
...                                                  ...
34863                              Председательствующий.
34864  Председательствующий. Нет, Владимир Борисович,...
34865                              Председательствующий.
34866  Председательствующий. Снимаете? Снял. Хорошо. ...
34867                              Председательствующий.

[34868 rows x 1 columns]

In [255]:
splitText = df['text'].str.split('((\w+ [А-Я|A-Z].[А-Я|A-Z].,)|(Председательствующий.))', n=1, expand = True)


In [256]:
splitText[:6]

0                      1  \
0  11 января 1994\n\n\nЗАСЕДАНИЕ ПЕРВОЕ\nЗдание Г...                   None   
1                                                     Председательствующий.   
2                                                     Председательствующий.   
3                                                             Апарина А.В.,   
4                                                             Апарина А.В.,   
5                                                     Председательствующий.   

               2                      3  \
0           None                   None   
1           None  Председательствующий.   
2           None  Председательствующий.   
3  Апарина А.В.,                   None   
4  Апарина А.В.,                   None   
5           None  Председательствующий.   

                                                   4  
0                                               None  
1                                                     
2   Дорогие депутаты Государственной Думы! Прошу ...  
3                                                     
4   избирательное объединение "Коммунистическая п...  
5

In [257]:
splitText = splitText.drop(columns = [0, 2, 3],axis = 1)
splitText
# Удаление лишних столбцов

1  \
0                       None   
1      Председательствующий.   
2      Председательствующий.   
3              Апарина А.В.,   
4              Апарина А.В.,   
...                      ...   
34863  Председательствующий.   
34864  Председательствующий.   
34865  Председательствующий.   
34866  Председательствующий.   
34867  Председательствующий.   

                                                       4  
0                                                   None  
1                                                         
2       Дорогие депутаты Государственной Думы! Прошу ...  
3                                                         
4       избирательное объединение "Коммунистическая п...  
...                                                  ...  
34863                                                     
34864   Нет, Владимир Борисович, уже были возражения....  
34865                                                     
34866   Снимаете? Снял. Хорошо. Прошу Вас.\nИсаков В....  
34867                                                     

[34868 rows x 2 columns]

In [258]:
splitText.rename(columns={1: 'name'}, inplace=True)
splitText.rename(columns={4: 'text'}, inplace=True)
splitText

name  \
0                       None   
1      Председательствующий.   
2      Председательствующий.   
3              Апарина А.В.,   
4              Апарина А.В.,   
...                      ...   
34863  Председательствующий.   
34864  Председательствующий.   
34865  Председательствующий.   
34866  Председательствующий.   
34867  Председательствующий.   

                                                    text  
0                                                   None  
1                                                         
2       Дорогие депутаты Государственной Думы! Прошу ...  
3                                                         
4       избирательное объединение "Коммунистическая п...  
...                                                  ...  
34863                                                     
34864   Нет, Владимир Борисович, уже были возражения....  
34865                                                     
34866   Снимаете? Снял. Хорошо. Прошу Вас.\nИсаков В....  
34867                                                     

[34868 rows x 2 columns]

In [259]:
splitText1 = splitText.replace(to_replace ="", value =np.nan)
splitText1

name  \
0                       None   
1      Председательствующий.   
2      Председательствующий.   
3              Апарина А.В.,   
4              Апарина А.В.,   
...                      ...   
34863  Председательствующий.   
34864  Председательствующий.   
34865  Председательствующий.   
34866  Председательствующий.   
34867  Председательствующий.   

                                                    text  
0                                                   None  
1                                                    NaN  
2       Дорогие депутаты Государственной Думы! Прошу ...  
3                                                    NaN  
4       избирательное объединение "Коммунистическая п...  
...                                                  ...  
34863                                                NaN  
34864   Нет, Владимир Борисович, уже были возражения....  
34865                                                NaN  
34866   Снимаете? Снял. Хорошо. Прошу Вас.\nИсаков В....  
34867                                                NaN  

[34868 rows x 2 columns]

In [260]:
splitText1 = splitText1.dropna(axis='index', how='any', subset=['text'])
splitText1

name  \
2      Председательствующий.   
4              Апарина А.В.,   
6      Председательствующий.   
8      Председательствующий.   
10           Иванченко А.В.,   
...                      ...   
34858  Председательствующий.   
34860  Председательствующий.   
34862  Председательствующий.   
34864  Председательствующий.   
34866  Председательствующий.   

                                                    text  
2       Дорогие депутаты Государственной Думы! Прошу ...  
4       избирательное объединение "Коммунистическая п...  
6       Возражений нет. (Все встают. Минута молчания....  
8       После заслушивания приветственного выступлени...  
10      заместитель Председателя Центральной избирате...  
...                                                  ...  
34858   Вот Вешняков Александр Альбертович. Поднимите...  
34860   Ольга Кирилловна, покажитесь, пожалуйста. Вот...  
34862      Нет.\nИсаков В.Б. ...что пять кандидатур...\n  
34864   Нет, Владимир Борисович, уже были возражения....  
34866   Снимаете? Снял. Хорошо. Прошу Вас.\nИсаков В....  

[17433 rows x 2 columns]

In [261]:
splitText1['text_length']  = splitText1['text'].str.len()

splitText1

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


name  \
2      Председательствующий.   
4              Апарина А.В.,   
6      Председательствующий.   
8      Председательствующий.   
10           Иванченко А.В.,   
...                      ...   
34858  Председательствующий.   
34860  Председательствующий.   
34862  Председательствующий.   
34864  Председательствующий.   
34866  Председательствующий.   

                                                    text  text_length  
2       Дорогие депутаты Государственной Думы! Прошу ...         3499  
4       избирательное объединение "Коммунистическая п...          398  
6       Возражений нет. (Все встают. Минута молчания....         7638  
8       После заслушивания приветственного выступлени...          854  
10      заместитель Председателя Центральной избирате...        16129  
...                                                  ...          ...  
34858   Вот Вешняков Александр Альбертович. Поднимите...         1615  
34860   Ольга Кирилловна, покажитесь, пожалуйста. Вот...         2827  
34862      Нет.\nИсаков В.Б. ...что пять кандидатур...\n           44  
34864   Нет, Владимир Борисович, уже были возражения....          195  
34866   Снимаете? Снял. Хорошо. Прошу Вас.\nИсаков В....          296  

[17433 rows x 3 columns]

In [262]:
splitText1['text_w_length']  = splitText1['text'].str.split().str.len()
splitText1

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


name  \
2      Председательствующий.   
4              Апарина А.В.,   
6      Председательствующий.   
8      Председательствующий.   
10           Иванченко А.В.,   
...                      ...   
34858  Председательствующий.   
34860  Председательствующий.   
34862  Председательствующий.   
34864  Председательствующий.   
34866  Председательствующий.   

                                                    text  text_length  \
2       Дорогие депутаты Государственной Думы! Прошу ...         3499   
4       избирательное объединение "Коммунистическая п...          398   
6       Возражений нет. (Все встают. Минута молчания....         7638   
8       После заслушивания приветственного выступлени...          854   
10      заместитель Председателя Центральной избирате...        16129   
...                                                  ...          ...   
34858   Вот Вешняков Александр Альбертович. Поднимите...         1615   
34860   Ольга Кирилловна, покажитесь, пожалуйста. Вот...         2827   
34862      Нет.\nИсаков В.Б. ...что пять кандидатур...\n           44   
34864   Нет, Владимир Борисович, уже были возражения....          195   
34866   Снимаете? Снял. Хорошо. Прошу Вас.\nИсаков В....          296   

       text_w_length  
2                445  
4                 46  
6                970  
8                104  
10              1955  
...              ...  
34858            227  
34860            389  
34862              6  
34864             29  
34866             38  

[17433 rows x 4 columns]

**Делаем сентимент анализ речей**

In [163]:
t = "Мать, двое ее сыновей и сестра погибли в квартире дома в подмосковном Долгопрудном".lower()
data = tokenizer.texts_to_sequences([t])
data_pad = pad_sequences(data, maxlen=max_text_len)
print( sequence_to_text(data[0]) )

res = model.predict(data_pad)
print(res, np.argmax(res), sep='\n')

['ее', 'и', 'в', 'дома', 'в']
[[0.16799133 0.8320087 ]]
1


In [164]:
t = "Спасибо, Александр Алексеевич. Мы тоже".lower()
data = tokenizer.texts_to_sequences([t])
data_pad = pad_sequences(data, maxlen=max_text_len)
print( sequence_to_text(data[0]) )

res = model.predict(data_pad)
print(res, np.argmax(res), sep='\n')

['спасибо', 'мы', 'тоже']
[[0.9470824  0.05291755]]
0


In [263]:
def senti(x):
    t = x.lower()
    data = tokenizer.texts_to_sequences([t])
    data_pad = pad_sequences(data, maxlen=max_text_len)
    #print( sequence_to_text(data[0]) )
    res = model.predict(data_pad)
    #print(res, np.argmax(res), sep='\n')
    return res 

splitText1['senti_score'] = splitText1['text'].apply(senti)

splitText1.to_csv('1994.csv', encoding='utf-8')

splitText1

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.


name  \
2      Председательствующий.   
4              Апарина А.В.,   
6      Председательствующий.   
8      Председательствующий.   
10           Иванченко А.В.,   
...                      ...   
34858  Председательствующий.   
34860  Председательствующий.   
34862  Председательствующий.   
34864  Председательствующий.   
34866  Председательствующий.   

                                                    text  text_length  \
2       Дорогие депутаты Государственной Думы! Прошу ...         3499   
4       избирательное объединение "Коммунистическая п...          398   
6       Возражений нет. (Все встают. Минута молчания....         7638   
8       После заслушивания приветственного выступлени...          854   
10      заместитель Председателя Центральной избирате...        16129   
...                                                  ...          ...   
34858   Вот Вешняков Александр Альбертович. Поднимите...         1615   
34860   Ольга Кирилловна, покажитесь, пожалуйста. Вот...         2827   
34862      Нет.\nИсаков В.Б. ...что пять кандидатур...\n           44   
34864   Нет, Владимир Борисович, уже были возражения....          195   
34866   Снимаете? Снял. Хорошо. Прошу Вас.\nИсаков В....          296   

       text_w_length                   senti_score  
2                445      [[0.782014, 0.21798596]]  
4                 46     [[0.15860404, 0.8413959]]  
6                970      [[0.6407422, 0.3592578]]  
8                104   [[0.98550564, 0.014494341]]  
10              1955     [[0.8686679, 0.13133213]]  
...              ...                           ...  
34858            227  [[0.99999166, 8.399755e-06]]  
34860            389    [[0.72493917, 0.27506083]]  
34862              6     [[0.9555501, 0.04444991]]  
34864             29      [[0.7404999, 0.2595001]]  
34866             38     [[0.8539487, 0.14605133]]  

[17433 rows x 5 columns]

In [ ]:
#splitText1.to_csv('2019.csv', encoding='utf-8')

# Подготовка тренировочных данных

In [ ]:
dfsum = pd.read_csv('doc_summary.csv', sep='delimiter', header=None)

/usr/local/lib/python3.7/dist-packages/pandas/util/_decorators.py:311: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  return func(*args, **kwargs)


In [ ]:
splitTextsum = dfsum[0].str.split(';', n=1, expand = True)

In [ ]:
splitTextsum.drop(df.head(1).index, inplace=True)
splitTextsum

0   1
1      Но при мужчине ни одна приличная женщина не по...  -1
2      Украина это часть Руси искусственно отделенная...  -1
3      Как можно говорить об относительно небольшой к...  -1
4      1.2014.  а что они со своими поляками сделали?...   0
5      у а фильмы... Зрители любят диковинное.   у ме...   0
...                                                  ...  ..
26869  Многих заставляют. Многие сами проявляют излиш...  -1
26870  Очередной Чубайс.  ну а чего нового то? Сорос ...  -1
26871  Закон, как все предыдущие - абсолютный бред и ...   0
26872  дело которое ты делаешь сейчас - оно очень хор...   0
26873  Рядом с Токио, да, мало пальм :) Зато на Окина...   0

[26873 rows x 2 columns]

In [ ]:
type(splitTextsum[1])

pandas.core.series.Series

## **Используем TensorFlow**
>
1.   Новый пункт
2.   Новый пункт



In [26]:
import os

In [ ]:
#import numpy as np

In [ ]:
#conda install numpy

In [ ]:
#conda install -c intel mkl

In [27]:
from tensorflow.keras.layers import Dense, LSTM, Input, Dropout, Embedding

In [28]:
from tensorflow.keras.models import Sequential

In [29]:
from tensorflow.keras.optimizers import Adam

In [30]:
from tensorflow.keras.preprocessing.text import Tokenizer, text_to_word_sequence

In [31]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [32]:
with open('train_data_t_New', 'r', encoding='utf-8') as f:
    texts_true = f.readlines()
    texts_true[0] = texts_true[0].replace('\ufeff', '') #убираем первый невидимый символ

with open('train_data_f_New', 'r', encoding='utf-8') as f:
    texts_false = f.readlines()
    texts_false[0] = texts_false[0].replace('\ufeff', '') #убираем первый невидимый символ

texts = texts_true + texts_false
count_true = len(texts_true)
count_false = len(texts_false)
total_lines = count_true + count_false
print(count_true, count_false, total_lines)

16090 10737 26827


In [33]:
maxWordsCount = 1000
tokenizer = Tokenizer(num_words=maxWordsCount, filters='!–"—#$%&amp;()*+,-./:;<=>?@[\\]^_`{|}~\t\n\r«»', lower=True, split=' ', char_level=False)
tokenizer.fit_on_texts(texts)

dist = list(tokenizer.word_counts.items())
print(dist[:10])
print(texts[0][:100])

[('1', 3779), ('2014', 127), ('а', 51269), ('что', 57760), ('они', 10761), ('со', 3593), ('своими', 552), ('поляками', 30), ('сделали', 525), ('русских', 975)]
1.2014.  а что они со своими поляками сделали?! русских, понятно. Но вот литовские поляки они все та


In [34]:
max_text_len = 10
data = tokenizer.texts_to_sequences(texts)
data_pad = pad_sequences(data, maxlen=max_text_len)
print(data_pad)

[[940  11 367 ... 463 553   2]
 [  1   3   3 ... 206  60   7]
 [114   6  65 ... 346 208   1]
 ...
 [ 37 614 933 ... 806   7   3]
 [ 15  15  33 ...  67 116  87]
 [313 660  26 ...  31 208  22]]


In [35]:
print( list(tokenizer.word_index.items()) )

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [36]:
X = data_pad
Y = np.array([[1, 0]]*count_true + [[0, 1]]*count_false)
print(X.shape, Y.shape)

(26827, 10) (26827, 2)


In [37]:
indeces = np.random.choice(X.shape[0], size=X.shape[0], replace=False)
X = X[indeces]
Y = Y[indeces]


model = Sequential()
model.add(Embedding(maxWordsCount, 128, input_length = max_text_len))
model.add(LSTM(128, return_sequences=True))
model.add(LSTM(64))
model.add(Dense(2, activation='softmax'))
model.summary()

model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer=Adam(0.0001))

history = model.fit(X, Y, batch_size=32, epochs=50)

reverse_word_map = dict(map(reversed, tokenizer.word_index.items()))

def sequence_to_text(list_of_indices):
    words = [reverse_word_map.get(letter) for letter in list_of_indices]
    return(words)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 10, 128)           128000    
                                                                 
 lstm (LSTM)                 (None, 10, 128)           131584    
                                                                 
 lstm_1 (LSTM)               (None, 64)                49408     
                                                                 
 dense (Dense)               (None, 2)                 130       
                                                                 
Total params: 309,122
Trainable params: 309,122
Non-trainable params: 0
_________________________________________________________________
Epoch 1/50
839/839 [==============================] - 30s 29ms/step - loss: 0.6700 - accuracy: 0.5999
Epoch 2/50
839/839 [==============================] - 23s 28ms/step - loss: 0.65

In [38]:
t = "Мать, двое ее сыновей и сестра погибли в квартире дома в подмосковном Долгопрудном".lower()
data = tokenizer.texts_to_sequences([t])
data_pad = pad_sequences(data, maxlen=max_text_len)
print( sequence_to_text(data[0]) )

res = model.predict(data_pad)
print(res, np.argmax(res), sep='\n')
print(res, '888888')
#[[0.14648964 0.8535104 ]]

['ее', 'и', 'в', 'дома', 'в']
[[0.16799133 0.8320087 ]]
1
[[0.16799133 0.8320087 ]] 888888
